"""add phone number

Revision ID: 3be63407bc4e
Revises: 91e9fcfa7d95
Create Date: 2021-11-20 18:43:53.026969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3be63407bc4e"
down_revision = "91e9fcfa7d95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
